# =============================================================================
# Chapter 3: Loads and Load Combinations — document builder.
#
# Migrated: all 7 tables built from structured LoadFacts.
# Fact builders (facts/loads.py) handle IRC6 calculations.
# Document builder only creates Table components — no IRC6 calls.
# =============================================================================

from ..document import Chapter, Column, RawLatex, Section, Table
from ..facts import ReportFacts
from ..facts.loads import build_load_facts
from ..layout import LayoutHints


def build_chapter_3(facts: ReportFacts) -> Chapter:
    """Build Chapter 3: Loads and Load Combinations.

    Constructs LoadFacts from raw_input_dict (including IRC6 calculations),
    then builds semantic Table components for each load category.
    """
    load_facts = build_load_facts(facts.raw_input_dict or {})

    return Chapter(
        number=3,
        title="Loads and Load Combinations",
        sections=[
            Section(
                title="",
                level=2,
                components=[
                    RawLatex(r"\vspace{1em}"),
                    _dead_load_table(load_facts),
                    RawLatex(r"\vspace{1em}"),
                    _surfacing_load_table(load_facts),
                    RawLatex(r"\vspace{1em}"),
                    _live_load_table(load_facts),
                    RawLatex(r"\vspace{1em}"),
                    _wind_load_table(load_facts),
                    RawLatex(r"\vspace{1em}"),
                    _seismic_load_table(load_facts),
                    RawLatex(r"\vspace{1em}"),
                    _temperature_load_table(load_facts),
                    RawLatex(r"\vspace{1em}"),
                    _load_combination_table(load_facts),
                    RawLatex(
                        r"\noindent\textit{Note: All IRC 6 load combinations "
                        r"are auto-generated by OsdagBridge. User-defined custom "
                        r"combinations, if any, are appended.}"
                    ),
                ],
            ),
        ],
    )


# ---------------------------------------------------------------------------
# Table 3.1 — Dead Load / Self Weight
# ---------------------------------------------------------------------------

def _dead_load_table(lf) -> Table:
    dl = lf.dead_load
    return Table(
        caption="Dead Load -- Self Weight",
        label="",
        columns=[
            Column("Parameter", width="5.5cm"),
            Column("Value", width="10.0cm"),
        ],
        rows=[
            ["Steel Self-Weight Applied", _fmt(dl.steel_density)],
            ["Concrete Deck Weight", _fmt(dl.concrete_density)],
            ["Self-Weight Factor", _fmt(dl.self_weight_factor)],
        ],
        layout=LayoutHints(space_after_mm=4),
    )


# ---------------------------------------------------------------------------
# Table 3.2 — Dead Load for Surfacing (DW)
# ---------------------------------------------------------------------------

def _surfacing_load_table(lf) -> Table:
    sl = lf.surfacing_load
    wc_desc = f"{sl.wearing_course_material} x {_fmt(sl.wearing_course_thickness)}" if sl.wearing_course_material else ""
    return Table(
        caption="Dead Load for Surfacing (DW)",
        label="",
        columns=[
            Column("Parameter", width="5.5cm"),
            Column("Value", width="10.0cm"),
        ],
        rows=[
            ["Wearing Course Load", wc_desc],
            ["Additional SIDL (Crash Barrier)", f"{_fmt(sl.crash_barrier_load)} per barrier"],
            ["Railing Load", f"{_fmt(sl.railing_load)}"],
        ],
        layout=LayoutHints(space_after_mm=4),
    )


# ---------------------------------------------------------------------------
# Table 3.3 — Live Loads (LL)
# ---------------------------------------------------------------------------

def _live_load_table(lf) -> Table:
    ll = lf.live_load

    vehicles_str = ", ".join(v.vehicle_class for v in ll.vehicles) if ll.vehicles else "None"

    # Impact factors — one entry per vehicle group
    im_parts = []
    seen_im = set()
    for v in ll.vehicles:
        if v.impact_factor and v.impact_factor.value is not None:
            key = v.impact_factor.value
            if key not in seen_im:
                seen_im.add(key)
                im_parts.append(f"{v.vehicle_class}: {v.impact_factor.value:.3f}")
    im_str = ", ".join(im_parts) if im_parts else "N/A"

    braking_str = _fmt(ll.braking_force) if ll.braking_force else "N/A"

    fp_str = "N/A"
    if ll.footway_load:
        fp_str = f"{_fmt(ll.footway_load.intensity)} ({ll.footway_load.load_type})"

    return Table(
        caption="Live Loads (LL)",
        label="",
        columns=[
            Column("Parameter", width="5.5cm"),
            Column("Value", width="10.0cm"),
        ],
        rows=[
            ["Vehicles Considered", vehicles_str],
            ["Impact Factor (IRC 6)", im_str],
            ["Braking Load (IRC 6)", braking_str],
            ["Footpath Live Load (if applicable)", fp_str],
        ],
        layout=LayoutHints(space_after_mm=4),
    )


# ---------------------------------------------------------------------------
# Table 3.4 — Wind Load (WL)
# ---------------------------------------------------------------------------

def _wind_load_table(lf) -> Table:
    wl = lf.wind_load
    return Table(
        caption="Wind Load (WL) --- per IRC 6",
        label="",
        columns=[
            Column("Parameter", width="5.5cm"),
            Column("Value", width="10.0cm"),
        ],
        rows=[
            ["Basic Wind Speed, Vb", f"{_fmt(wl.basic_wind_speed)} [from Project Location]"],
            ["Terrain Type", wl.terrain_type or "N/A"],
            ["Average Exposed Height, H (m)", _fmt(wl.avg_exposed_height)],
            ["Hourly Mean Wind Speed, Vz", _fmt(wl.hourly_mean_wind_speed)],
            ["Hourly Wind Pressure, Pz", _fmt(wl.hourly_wind_pressure)],
            ["Transverse Wind Force", _fmt(wl.transverse_wind_force)],
            ["Longitudinal Wind Force", _fmt(wl.longitudinal_wind_force)],
            ["Vertical Wind Force", _fmt(wl.vertical_wind_force)],
        ],
        layout=LayoutHints(space_after_mm=4),
    )


# ---------------------------------------------------------------------------
# Table 3.5 — Earthquake Load (EL)
# ---------------------------------------------------------------------------

def _seismic_load_table(lf) -> Table:
    sl = lf.seismic_load
    return Table(
        caption="Earthquake Load (EL) --- per IRC 6",
        label="",
        columns=[
            Column("Parameter", width="5.5cm"),
            Column("Value", width="10.0cm"),
        ],
        rows=[
            ["Seismic Zone", f"{sl.seismic_zone} [from Project Location]"],
            ["Zone Factor, Z", _fmt(sl.zone_factor)],
            ["Importance Factor, I", _fmt(sl.importance_factor)],
            ["Type of Soil", sl.soil_type or "N/A"],
            ["Sa/g", _fmt(sl.spectral_coeff)],
            ["Horizontal Seismic Coefficient, Ah", _fmt(sl.horizontal_coeff)],
            ["Vertical Seismic Coefficient, Av", _fmt(sl.vertical_coeff)],
            ["Horizontal Seismic Force (longitudinal)", _fmt(sl.horizontal_force_long) if sl.horizontal_force_long else "N/A"],
            ["Horizontal Seismic Force (transverse)", _fmt(sl.horizontal_force_trans) if sl.horizontal_force_trans else "N/A"],
        ],
        layout=LayoutHints(space_after_mm=4),
    )


# ---------------------------------------------------------------------------
# Table 3.6 — Temperature Load (TL)
# ---------------------------------------------------------------------------

def _temperature_load_table(lf) -> Table:
    tl = lf.temperature_load
    bridge_range = f"{_fmt(tl.bridge_temp_min)} to {_fmt(tl.bridge_temp_max)}" if tl.bridge_temp_min.value is not None else "N/A"
    rise_fall = f"+{_fmt(tl.temp_rise)} / -{_fmt(tl.temp_fall)}" if tl.temp_rise.value is not None else "N/A"
    return Table(
        caption="Temperature Load (TL) --- per IRC 6",
        label="",
        columns=[
            Column("Parameter", width="5.5cm"),
            Column("Value", width="10.0cm"),
        ],
        rows=[
            ["Maximum Shade Temperature", _fmt(tl.max_shade_temp)],
            ["Minimum Shade Temperature", _fmt(tl.min_shade_temp)],
            ["Effective Bridge Temp. Range", bridge_range],
            ["Temperature Rise / Fall for Design", rise_fall],
        ],
        layout=LayoutHints(space_after_mm=4),
    )


# ---------------------------------------------------------------------------
# Table 3.7 — Load Combinations
# ---------------------------------------------------------------------------

def _load_combination_table(lf) -> Table:
    rows = []
    for combo in lf.load_combinations:
        parts = []
        for entry in combo.factors:
            label = entry[0]
            add = entry[1]
            rel = entry[2]
            if rel is not None:
                add_s = f"{add:.2f}" if add is not None else "--"
                rel_s = f"{rel:.2f}" if rel is not None else "--"
                parts.append(f"{label}({add_s}/{rel_s})")
            else:
                if add is None:
                    continue
                parts.append(f"{label}({add:.2f})")
        rows.append([combo.combination_id, " + ".join(parts)])

    return Table(
        caption="Load Combinations",
        label="",
        columns=[
            Column("Combination ID", width="4.0cm"),
            Column("Load Cases", width="11.5cm"),
        ],
        rows=rows,
        layout=LayoutHints(space_after_mm=4),
    )


# ---------------------------------------------------------------------------
# Formatting helper
# ---------------------------------------------------------------------------

def _fmt(qv) -> str:
    """Format a QuantityValue for display. None → 'N/A'."""
    if qv is None or qv.value is None:
        return "N/A"
    if qv.unit:
        return f"{qv.value:.4g} {qv.unit}"
    return f"{qv.value:.4g}"
